### ISSUE TITLE
Provide proper setup

### ISSUE THREAD

**Issue by clelange** [PascalBaertschi/tau-regression#2]
Please provide a proper setup in the documentation. The environment described in the README is incomplete, e.g. missing `scikit-learn`.

Here is how I got things to work on the PSI T3:

```shell
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
sh Miniconda2-latest-Linux-x86_64.sh
```

Follow the instructions, no changes to default arguments.

```shell
conda create --name=taureg python=2 keras tensorflow pandas scikit-learn
source activate taureg
```

Then run `python nn_github.py`.

**Comment by PascalBaertschi** [comment]
README now contains setup to run all of the codes.
